### ISSUE TITLE
TODO list before beta 0.2

### ISSUE THREAD

**Issue by matrefeytontias** [matrefeytontias/nKaruga-deprecated-Nspire-version-#15]
Overall, the second level must be fully playable, including the boss. I'll only say it once, but each level uses a different mechanics than the others: while level 1 is a "normal" scrolling level with enemies, level 2 has varying backgrounds and scrolling speeds (two actually) and props. It also needs a slightly more complex transition (probably a rotating background blitting).
- [ ] Implement support for interactive environment elements (walls, props ...). Those are probably going to be normal enemies with a "isEnvironment" flag set, preventing them from having any sort of behavior other than staying in place, and from dying (except for crates). This should prevent code duplication without any other performance hit than a flag test.
- [ ] Implement independent camera movement (don't take background scrolling into account)
  - [x] Constantly keep absolute camera coordinates and coordinates that are relative to the point where the enemy wave started. This will permit enemies that have pseudo-relative coordinates and environment elements that have absolute coordinates to interact.
  - [x] Add rendering hook to account for camera position, which was made possible (easy ?) with the implementation of drawing candidates.
  - [x] Slightly modify level 1 patterns to cope with the camera system. Shouldn't be too hard considering the camera can stay in place just for this level.
  - [ ] Make the player unable to go out of the camera field.
- [ ] Write new patterns for new enemies
- [ ] Create new sprites for new enemies
- [ ] Write boss 2's patterns
- [ ] Create and animate boss 2's sprites
  On other subjects:
- [ ] Add the ability to use 2-4-6-8 for movement, instead of only the touchpad or clickpad.
- [ ] Improve code quality with inheritance. Yes, I knew its existence before, but recently learnt how to properly use it.

The good news is that the vast majority of the engine was already done for level 1. Hopefully, less and less things (besides sprites and patterns) will need to be added for each level.
