### ISSUE TITLE
TODO list before beta 0.1

### ISSUE THREAD

**Issue by matrefeytontias** [matrefeytontias/nKaruga-deprecated-Nspire-version-#5]
What's left to reach milestone.
- [x] Write player engine
  - [x] Movement with clickpad or touchpad
  - [x] Timed single-then-double fire
  - [x] Power releases
  - [x] Death
- [x] Write bullets engine
  - [x] Player bullets
  - [x] Player and enemy power fragments
  - [x] Enemy bullets
  - [x] Enemy homing lasers
  - [x] Enemy heavy lasers
  - [x] Collisions between player bullets/power fragments and enemies
  - [x] Collisions between enemy bullets/power fragments and player
  - [x] Collisions between player and homing lasers
  - [x] Collisions between player and heavy laser
- [x] Write enemies engine
  - [x] Handling and drawing enemies
  - [x] Killing enemies
  - [x] Enemy fire
  - [x] Fire-back
  - [x] Using custom AI for each enemy
  - [x] Assigning an enemy to a parent enemy for relative positioning
  - [x] Collisions with player
- [x] Write level stream parser
  - [x] Spawning enemies
  - [x] Spawning bosses
  - [x] Separating introduction and level
  - [x] Special commands:
    - [x] Pauses
    - [x] Waiting for every enemy to be killed and/or being off-screen
    - [x] Starting a new wave
    - [x] Doing a transition between introduction and actual level
    - [x] Jointing enemies
    - [x] Breakpoints for debugging
- [x] Pause button for emulation
- [x] Write full level 1 stream (partially done)
- [x] Write inline menu in title screen
- [x] Use a configuration file
  - [x] Read/write custom controls
  - [x] Read/write last difficulty
  - [x] Read/write use of touchpad
  - [x] Read/write use of scrolling background
- [x] Have customizable controls
- [x] Display end-of-level results
- [x] "Dot eater" achievement : finish the level without firing once
- [x] Have all graphics for level 1 (lacks player's explosion sprites)
- [x] Have graphics for boss
- [x] Fight boss

**Comment by QuanticPotato** [comment]
I'm working on the player/enemies collisions task.

**Comment by matrefeytontias** [comment]
Currently working on the inline menu.

**Comment by matrefeytontias** [comment]
Validated inline menu, config file and customizable controls with 098e8c25f1f2f00e0bd9764c30875c81ff8d85de

**Comment by matrefeytontias** [comment]
I've expanded the TODO list to give more info on the config file.

**Comment by matrefeytontias** [comment]
Finished config file implementation with c8031ceb9c8be2a96dd9e0979e0a9e7a4b03ba46

**Comment by matrefeytontias** [comment]
Finished chapter 1 stream ! :D

**Comment by matrefeytontias** [comment]
Updated issue ; player death still needs to be written.

**Comment by matrefeytontias** [comment]
Done with 0057058d8764a280662f4447c0f18a6dc6193641

**Comment by matrefeytontias** [comment]
Finished bullet engine with 59acc01559d19522c003b03bdd0a0bb96696b547

**Comment by matrefeytontias** [comment]
Thanks for finishing the enemies engine with #9

**Comment by matrefeytontias** [comment]
EOL results done with 4ed358e403724151ca2fd6357791a0ef0790cc74

**Comment by matrefeytontias** [comment]
All boss 1 sprites are done with 5e47c63942045c3c6e0e9a7bc53910214186fa42

**Comment by matrefeytontias** [comment]
Milestone reached !

**Comment by QuanticPotato** [comment]
Nice :)
